### PR TITLE
traffic-policy: T4688: add support for limiter exceed/notexceed actions

### PR DESCRIPTION
**Pull request by initramfs**
## Change Summary

Adds configuration nodes to set the exceed action and the non-exceed action for the limiter traffic policy for additional customization with respect to what the limiter can do (currently it can only drop packets exceeding the configured bandwidth). Uses cases for this are listed in the Phabricator task.

Documentation update PR is [here](https://github.com/vyos/vyos-documentation/pull/852).

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)
* https://phabricator.vyos.net/T4688

## Component(s) name
traffic-policy

## Proposed changes
Adds new configuration nodes `exceed-action` and `notexceed-action` (names taken from tc-police(8)) to the default and all class nodes under the limiter traffic-policy. An example config is shown below:
```
traffic-policy {
    limiter test {
        default {
            bandwidth 1gbit

            exceed-action drop
            notexceed-action ok
        }

        class 100 {
            bandwidth 500mbit
            priority 1

            exceed-action reclassify
            notexceed-action ok
        }
    }
}
```

## How to test

1. Create a limiter traffic-policy using a configuration similar to the one given above
2. Apply the traffic-policy to an interface's ingress direction
3. Run: `tc filter show dev <iface> ingress` to validate the `conform-exceed` keyword is populated with the correct action(s).

## Checklist:
- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by zdc** [comment]
Hi, @initramfs! Thanks for the PR!
Could you provide a more complex use-case with an example configuration where new options can be used with `tc` outputs?

**Comment by initramfs** [comment]
An example configuration:
```
interfaces {
    input ifb0 {
        traffic-policy {
            out codel0
        }
    }

    ethernet eth0 {
        traffic-policy {
            in limiter0
        }
    }
}

traffic-policy {
    fq-codel codel0 {
    }

    limiter limiter0 {
        class 50 {
            bandwidth 100mbit
            match m1 {
                ip {
                    destination {
                        port 22
                    }
                }
            }
            notexceed-action continue
            priority 1
        }

        default {
            bandwidth 200mbit
            notexceed-action continue
        }
    }
}
```

Along with executing (from a post-config script or any other mechanism):
```
tc filter add dev eth0 parent ffff: prio 1000 matchall action mirred egress redirect dev ifb0
```
Note: we technically should be able to use the `redirect` configuration directive here, but there's currently a validation step that prohibits using an ingress qdisc with a redirect. This restriction can be relaxed after this PR is merged.

Allows for the use of limiter 'classes' to limit destination port 22 traffic to 100 mbit but still engage the fq-codel AQM after the limit.
`tc qdisc show`:
```
qdisc pfifo_fast 0: dev eth0 root refcnt 2 bands 3 priomap  1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1
qdisc ingress ffff: dev eth0 parent ffff:fff1 ----------------
qdisc fq_codel 8002: dev ifb0 root refcnt 2 limit 10240p flows 1024 quantum 1514 target 5.0ms interval 100.0ms memory_limit 32Mb 
```
`tc filter show dev eth0 ingress`:
```
filter parent ffff: protocol all pref 1 u32 chain 0 
filter parent ffff: protocol all pref 1 u32 chain 0 fh 800: ht divisor 1 
filter parent ffff: protocol all pref 1 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid ffff:32 not_in_hw 
  match 00000050/0000ffff at 20
	action order 1:  police 0x4 rate 50Mbit burst 15Kb mtu 2Kb action drop/continue overhead 0b 
	ref 1 bind 1

filter parent ffff: protocol all pref 255 basic chain 0 
filter parent ffff: protocol all pref 255 basic chain 0 handle 0x1 flowid ffff:33 
	action order 1:  police 0x3 rate 100Mbit burst 15337b mtu 2Kb action drop/continue overhead 0b 
	ref 1 bind 1

filter parent ffff: protocol all pref 1000 matchall chain 0 
filter parent ffff: protocol all pref 1000 matchall chain 0 handle 0x1 
  not_in_hw
	action order 1: mirred (Egress Redirect to device ifb0) stolen
 	index 2 ref 1 bind 1
```
We can also replace the `ifb0` qdisc with anything else (especially if we're open to using scripts), such as `cake` or `htb` or `prio`).

The final mirred redirect action could also be to a monitoring interface (where we use `exceed-action continue` instead in the configuration), this will allow said monitoring interface to receive all excess traffic (DoS/flood diagnostics).

We could also use the `tc actions ...` based commands (in a postconfig script or otherwise) to append actions onto existing filters (where the use of `exceed-action`/`notexceed-action` pipe might be useful).

<hr>

I submitted this PR as I am personally using something similar to the above where a limiter is followed by the `cake` qdisc to provide classful ingress limiting and shaping based on match parameters I can define; and the less stuff that exists in a custom postconfig script the better.

**Comment by zdc** [comment]
Thanks!

It makes sense. But to merge this, we need to add the same feature into 1.4 first. Configuration must be compatible for 1.3 -> 1.4 updates.
Could you do this?

You need to add the same changes to branch `current` in this repo, and update XML definitions for future implementation:
https://github.com/vyos/vyos-1x/blob/current/interface-definitions/qos.xml.in

**Comment by initramfs** [comment]
Perhaps I am wrong but QoS seems to be getting a complete rewrite to python/XML in 1.4, where, as of the time of writing, the python parts still seem largely unimplemented. I could submit a PR to just update the XML parts but I guess whoever is currently implementing the python parts will need to implement said feature.

I am willing to help with the implement QoS in 1.4 though I'd definitely need to collaborate with whoever is responsible for that right now.

**Comment by zdc** [comment]
You are completely right. Changes in XML actually are required only to be sure that old and new implementations will be in sync with the syntax. We all are just people, and I am worried about not missing anything in the middle of the migration. Taking into account that QoS is a part of the system that is not often changed and CLI was already migrated - a chance to forget about these new options is not really zero. :)

The more important is to add the new features to this repository. It is still used for 1.4 now. So, this PR updates 1.3 / `equuleus`, but the code for 1.4 / `current` must be updated as well, and actually, this must be done first to test changes before backporting them to 1.3: https://github.com/vyos/vyatta-cfg-qos/tree/current
Just create the same PR for the `current` branch.

**Comment by initramfs** [comment]
PR for the current branch has been added in #19. Additionally the new XML elements for current have been submitted as https://github.com/vyos/vyos-1x/pull/1547.

**Comment by initramfs** [comment]
Closing as per discussion in #19.

**Pull request closed without merging**
